### ISSUE TITLE
[Bug]: SectionCommenter breaks classes injected in a @yield

### ISSUE THREAD

**Issue by bjhijmans** [spatie/laravel-blade-paths#13]
### What happened?

We have a layout that lets you insert classes into the body using @yield and @section. But the section commenter makes the classes invalid.

### How to reproduce the bug

Have a page with a `@yield` for a class:
```
<body class="@yield('body-class')">
</body>
```

Then add a page that extends that layout and try to add classes:

```
@section('body-class', 'gray-bg login-page')
```

The resulting tag is as follows:

```
<body class="<!-- Start section: body-class -->gray-bg login-page<!-- End section: body-class -->">
```

Due to the placement of the comment tag, my browser (at least chrome and firefox) doesn't recognize the `gray-bg` and `login-page` classes. Adding a space before and after the HTML comments fixes the issue. Maybe there should always be a space around the comments?

### Package Version

1.0.3

### PHP Version

8.1.x

### Laravel Version

10.13.0

### Which operating systems does with happen with?

Linux

**Comment by timvandijck** [comment]
This is relatively similar to the problem described in #11. 

I'll defenitly be looking at implementing a blacklist feature as described there, and probably try to add a set of sensible default situations where to never add an HTML comment.
