### ISSUE TITLE
[Bug]: ParseError when using config() value for default in @yield

### ISSUE THREAD

**Issue by mortenscheel** [spatie/laravel-blade-paths#4]
### What happened?

This is valid blade:
```blade
<title>@yield('title', config('app.name'))</title>
```
But when laravel-blade-comments is installed, it causes a `ParseError` that doesn't seem to make much sense.
Screenshot:
![image](https://github.com/spatie/laravel-blade-comments/assets/6514342/fa9906fd-90a5-4b12-bed3-c9db6c2c4164)

### How to reproduce the bug

Create a simple blade layout file containing this title tag in the <head>
```php
<title>@yield('title', config('app.name'))</title>
```
Try to render a blade file that extends the layout.

Note: It doesn't matter if you override the 'title' section in the view or not.

### Package Version

1.0.0

### PHP Version

8.2.5

### Laravel Version

10.11.0

### Which operating systems does with happen with?

Linux

**Comment by timvandijck** [comment]
Nice catch, looks like the regex is incorrect for @yield that also passes a variable. I'm going to patch this.

**Comment by timvandijck** [comment]
@mortenscheel I pushed a minor update that should resolve your issue.
