### ISSUE TITLE
[Bug]: Can't install in laravel 9

### ISSUE THREAD

**Issue by jalso** [spatie/laravel-blade-paths#7]
### What happened?

I tried to add this package:
# composer require spatie/laravel-blade-comments:* --dev

./composer.json has been updated
Running composer update spatie/laravel-blade-comments
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires spatie/laravel-blade-comments * -> satisfiable by spatie/laravel-blade-comments[dev-main, 0.0.1, 1.0.0, 1.0.1, 9999999-dev].
    - spatie/laravel-blade-comments[dev-main, 0.0.1, 1.0.0, ..., 1.0.1] require illuminate/contracts ^10.0 -> found illuminate/contracts[v10.0.0, ..., 10.x-dev] but these were not loaded, likely because it conflicts with another require.

When I try to add illuminate/contracts, I cant:
`  Problem 1
    - Only one of these can be installed: laravel/framework[v9.0.0-beta.1, ..., 9.x-dev], illuminate/contracts[v10.0.0, ..., 10.x-dev]. laravel/framework replaces illuminate/contracts and thus cannot coexist with it.`

I this package not compatible with laravel 9? Thank You!

### How to reproduce the bug

I tried to install it in laravel 9.

### Package Version

1.01

### PHP Version

8.1.19

### Laravel Version

9.52.9

### Which operating systems does with happen with?

macOS

**Comment by timvandijck** [comment]
The package was created after Laravel 10 was released so that's what we based it on. Normally I would be hesitant to add support for older versions, but given the nature of the package I added Laravel 9 support to release 1.0.2. Enjoy!

**Comment by jalso** [comment]
Thank You!
