### ISSUE TITLE
[Bug]: assertInertia() always fails when blade comments are enabled

### ISSUE THREAD

**Issue by bsdnomad** [spatie/laravel-blade-paths#8]
### What happened?

Hi there,

I was headbanging a lot why some tests performing Inertia assertions began failing accidentally until I figured out it goes always like that when blade comments are enabled.

Disabling the extension in config/blade-comments.php allowing all the tests to pass successfully.
Hope that is going to save some time and prevent a lot of troubles to anybody impacted by the issue.

### How to reproduce the bug

Using a vanilla Jetstream + Inertia + Vue starter kit application installed do the following: 
1. Install the extension, publish config file as described in README page.
2. Make sure APP_DEBUG is set to true in (testing) .env file 
3. Create invokable controller, create a route, render a Inertia page with a Vue component, extending default AppLayout, having one simple nested component inside (just a plain html chunk in a <template> without any special features inside), like:
4. Make a controller test and test the page route, call assertInertia() method inside.
5. Execute the test.
6. Expect test to fail with a 'Not a valid Inertia response' message.
7. Turn off debugging by setting APP_DEBUG=false
8. Execute the test again.
9. Expect successful assertion/s.

The results are reproucible also with just any non-nested page component.

web.php:

```
Route::middleware([
    'auth:sanctum',
    config('jetstream.auth_session'),
    'verified',
])->group(function () {
    Route::get('/dashboard', function () {
        return Inertia::render('Dashboard');
    })->name('dashboard');

    // Add the following protected route
    Route::get('/sample', \App\Http\Controllers\MyInvokableController::class);
});

```

app/Http/Controllers/MyInvokableController.php:

```
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Inertia\Inertia;

class MyInvokableController extends Controller
{
    /**
     * Handle the incoming request.
     */
    public function __invoke(Request $request)
    {
        return Inertia::render('Sample/Show');
    }
}

```

tests/Feature/MyInvokableControllerTest.php:

```
<?php

namespace Tests\Feature;

use Inertia\Testing\AssertableInertia;
use Tests\TestCase;

/**
 * @group sample
 */
class MyInvokableControllerTest extends TestCase
{
    /**
     * A basic feature test example.
     */
    public function test_sample_page_has_desired_inertia_components(): void
    {
        $this->actingAs(\App\Models\User::factory()->create());

        $response = $this->get('/sample');

        $response->assertStatus(200);
        $this->assertAuthenticated();

        $response->assertInertia(fn(AssertableInertia $page) =>
            $page->component('Sample/Show', fn(AssertableInertia $page) =>
                $page->component('SectionBorder')
            )
        );
    }
}

```
resources/js/Pages/Show.vue:

```
<template>
    <AppLayout title="Sample Title">
        <template #header>
            <h2 class="font-semibold text-xl text-gray-800 dark:text-gray-200 leading-tight">
                Sample Page Title
            </h2>
        </template>

        <div>
            <div class="max-w-7xl mx-auto py-10 sm:px-6 lg:px-8">
                <SectionBorder />
            </div>
        </div>
    </AppLayout>
</template>
<script setup>
import AppLayout from '@/Layouts/AppLayout.vue'
import SectionBorder from '@/Components/SectionBorder.vue'
</script>

```

### Package Version

1.0.1

### PHP Version

8.1

### Laravel Version

10

### Which operating systems does with happen with?

Linux

**Comment by freekmurze** [comment]
I'd accept a PR that fixes this.

**Comment by timvandijck** [comment]
Given the package is not recommended to be used on a production application I wonder how relevant it would be to run tests with it being enabled.

Maybe we should just add a note in the README to set the package config to disabled in the base TestCase.

I'm happy to hear thoughts on this.

**Comment by bsdnomad** [comment]
Hi guys,

Actually that comes due to the way Inertia assertions work. Basically it expects a View object in the response while, after placing respective comments in the template contents that becomes a string, respectively 'page' attribute is missing and the assertion functions chain throws an exception the response is not a view. I'll dig deeper and try to suggest a solution.
